### PR TITLE
fix gaps between walls and sparse infill, issue #12304

### LINKED ISSUE #12304: Sparse Infill is not connected to a wall when ensure vertical shell thickness is true
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-beta

### Operating System (OS)

macOS

### OS Version

macOS 26.2

### Additional system information

_No response_

### Printer

Sovol SV08

### How to reproduce

1. New project
2. Add primitive "Sphere"
3. Cut the object in the middle, both parts "Place on cut"
4. Arrange all Objects
5. Change Strength -> Sparce Infill Density to 1%
6. Change Strength -> Sparce Infill Pattern to Grid
7. Slice
8. Check Layer 30

### Actual results

There is a gap between sparce infill and the wall

Image
Image

### Expected results

Sparce infill should be connected to the wall

### Project file & Debug log uploads

[Sphere.3mf.zip](https://github.com/user-attachments/files/25319297/Sphere.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

While this problem occurred only on layer 30, in my custom model,l it happens way more frequently 

Image

### PR DESCRIPTION
**Pull request by echipachenko**
# Description

This fixes issue #12304: gaps between walls and sparse infill.
When "Detect Narrow Infill" is enabled, sparse infill (Grid pattern) shows gaps between the infill lines and the walls.

**Root Cause:** In the `split_solid_surface()` function in `src/libslic3r/Fill/Fill.cpp`:
Line 656: The `inner_area` is shrunk by `scaled_spacing * 0.5` (minus overlap)
Line 813 (original): The normal infill is expanded by only `scaled_spacing * 0.1`

This creates a net inward shift of 0.4 * spacing, leaving a gap

**Solution:** Increase the expansion amount from scaled_spacing * 0.1 to scaled_spacing * 0.5 to match the shrinkage applied earlier. This ensures the normal infill properly covers the area and connects seamlessly with the narrow infill.

**Additional Context**
When "Ensure vertical shell thickness" triggers on sloping walls (e.g., spheres), it generates a Solid Infill band. This function separates the thin sections of that band. Expanding normal_infill by `scaled_spacing * 0.5` ensures the zig-zag paths physically overlap the concentric narrow lines by half a line width. This welds the plastic together during printing and prevents shrinkage gaps inside the shell.

# Screenshots/Recordings/Graphs

**Before fix:**

Screenshot 2026-03-15 о 2 54 26 пп
Screenshot 2026-03-15 о 2 54 35 пп

**After fix:**
When "Detect narrow internal solid infill" is **enabled**:
Screenshot 2026-03-15 о 3 51 00 пп

When "Detect narrow internal solid infill" is **disabled**:
Screenshot 2026-03-15 о 3 53 22 пп

## Tests

See attached screenshots.

**NOTE**:
This PR addresses the gaps between sparse infill and walls that occur when both `Detect narrow internal solid infill` and `Ensure vertical shell thickness` are enabled. While a gap remains when `Detect narrow internal solid infill` is disabled (where a zig-zag line is expected), this fix improves print quality for the primary use case. 
Additionally, these changes bring the output closer to the behaviour seen in Bambu Studio. Given the partial improvement, I believe this is ready for merge

Fix #12304

### CODE REVIEW

File: src/libslic3r/Fill/Fill.cpp [hunk 1]
```diff
@@ -808,8 +808,10 @@ void split_solid_surface(size_t layer_id, const SurfaceFill &fill, ExPolygons &n
         return;
     }
 
-    // Expand the normal infills a little bit to avoid gaps between normal and narrow infills
-    normal_infill = intersection_ex(offset_ex(normal_fill_areas_ex, scaled_spacing * 0.1), fill.expolygons);
+    // Expand the normal infills to avoid gaps between normal and narrow infills.
+    // The inner_area was shrunk by scaled_spacing * 0.5 (line 684), so we need to expand
```
Comment (RF47) [inline src/libslic3r/Fill/Fill.cpp]: I wouldn't refer to the line number, as the code changes all the time and the line might change

Comment (echipachenko) [reply src/libslic3r/Fill/Fill.cpp]: fixed

**Comment by echipachenko** [comment]
I need a few more hours/days to finish testing, I'll let you know if it's ready to be merged...

**Comment by RF47** [comment]
> I need a few more hours/days to finish testing, I'll let you know if it's ready to be merged...

I tried it, but for some reason I can't reproduce the issue.

**Comment by echipachenko** [comment]
Hi @RF47 , 

This PR addresses the gaps between sparse infill and walls that occur when both `Detect narrow internal solid infill` and `Ensure vertical shell thickness` are enabled. While a gap remains when `Detect narrow internal solid infill` is disabled (where a zig-zag line is expected), this fix improves print quality for the primary use case. 
Additionally, these changes bring the output closer to the behaviour seen in Bambu Studio. Given the partial improvement, I believe this is ready for merge

**Comment by RF47** [comment]
I cant reproduce the issue:
What am I doing wrong?
image
[Sphere.3mf.zip](https://github.com/user-attachments/files/26512742/Sphere.3mf.zip)

**Comment by echipachenko** [comment]
Hi @RF47 , Could you check line width for the solid infill? Try increasing it. Anyway, I was using default settings from Sovol sv08 profile. If I am not mistaken, it was using 0.5 for internal solid infill (or 0.45). I'll share my settings later today.

**Comment by RF47** [comment]
image

**Comment by echipachenko** [comment]
Hi @RF47 
[bug report.zip](https://github.com/user-attachments/files/26728822/bug.report.zip)
I've created a zip file with:
- gcode
- 3mf file
- version screenshot
- issue screenshot
Please take a look.
I am wondering if the issue is reproducible on ARM MacBooks only?...

**Comment by RF47** [comment]
very strange, same layer, different result.
Windows
image
Linux
image

**Comment by RF47** [comment]
> * I am wondering if the issue is reproducible on ARM MacBooks only?...

I really don't know why this is happening; could it be a rounding error that's being handled differently?

**Comment by SoftFever** [comment]
I can confirm the issue is reproducible on Mac, but Windows doesn't have this issue.

The change itself seems harmless to me, so I'll merge it for broader testing.

I've seen multiple PRs trying to manipulate "magic" margins recently. We'll take extra caution with such changes going forward.

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you
