### PR TITLE
[Feature] Introduced option to control amount of internal bridging, fixing internal bridge missing for some sloped surfaces

### LINKED ISSUE #413: Printing of slopes is missing the Bidge Layer
**Describe the bug**
If parts are printed with a slope in some cases the top surface gets messy. The Slicer is printing Internal solid Infill on the Infill layer, due to the Speed of the Internal solid Infill it's not working well. It should start with a Bridge Layer first, in some cases, the slicer is doing it.
I have made a video to illustrate the problem
https://youtu.be/SWV-gBCttPM

**3mf File for This Bug**
[Problem slope.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10880245/Problem.slope.zip)

**To Reproduce**
Slice attached Part.

**Expected behavior**
Bridge Lines should be printed first on the Infill, and on top of that comes the Internal solid Infill.

**Screenshots**
Screenshot 2023-03-03 095934

**Printer model**
see ZIP File

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Bambu Studio SoftFever 1.4.5 / Bambu Studio 1.4.2.13

### PR DESCRIPTION
**Pull request by igiannakas**
Updated below text with final ready for review implementation
---
Aiming to address issue https://github.com/SoftFever/OrcaSlicer/issues/413 and corresponding development backlog item

By default Orca and all the Slic3r derivatives implement filtering to remove areas where internal bridging may be unnecessary as the infill is thought to be supported adequately from the sparse infill below.

However that is not always the case, especially for:
1. Models with arched top surfaces
2. When lightning infill is used for curved top surface models
3. When low density infill is used and especially with curved/slanted top surfaces

So updated the PR to convert this into an option:

**Disabled (default) - Limited filtering - No filtering**
1. **Disabled** is the current behaviour and it is selected as the default value to maintain user experience continuity. 
2. **Limited filtering** addresses the majority of the slanted top surface issues without creating unnecessary internal bridges and is what I'll pick as my default. It is also enabled by default when lightning infill is used as this is particularly problematic. (and personally I've ruined a few silk PLA models because of this and had to significantly increase lightning infill % to get it to work well).
3. **No filtering** adds internal bridges on all internal overhangs. It is very aggressive in creating internal bridges but this solves issues with very specific models with a specific angle of slanted top surface as seen below.

The above options can be controlled on a **per-object basis**, so if any particularly problematic objects exist in the build plate they can be enabled for them only.

In the image below you can see the limited filtering addressing the problematic slope but the regular shaped Voron cube being completely unaffected. With no filtering, there is excess bridging on the Voron cube. However it addresses the issue with the subsequent model (see further down).
image

**No filtering for a challenging model:**
image

**Print test for the above model:**
**Left: Disabled - Right: No filtering**
IMG_2749

Fixes #413

### CODE REVIEW

File: src/libslic3r/PrintObject.cpp [hunk 1]
```diff
@@ -1989,12 +1988,20 @@ void PrintObject::bridge_over_infill()
     };
 
     std::map<size_t, std::vector<CandidateSurface>> surfaces_by_layer;
+    // Ioannis Giannakas:
```
Comment (SoftFever) [inline src/libslic3r/PrintObject.cpp:1991]: Hi Ioannis,
May I request that we stick to the convention of the `// Orca:` format?
Just so that it's easier for maintenance.

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:1991]: Of course!!!

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp]: done

File: src/libslic3r/PrintObject.cpp [hunk 2]
```diff
@@ -2017,14 +2024,18 @@ void PrintObject::bridge_over_infill()
...
-                lower_layer_solids = shrink(lower_layer_solids, 1 * spacing); // first remove thin regions that will not support anything
-                lower_layer_solids = expand(lower_layer_solids, (1 + 3) * spacing); // then expand back (opening), and further for parts supported by internal solids
-                // By shrinking the unsupported area, we avoid making bridges from narrow ensuring region along perimeters.
-                unsupported_area   = shrink(unsupported_area, 3 * spacing);
-                unsupported_area   = diff(unsupported_area, lower_layer_solids);
-
+                
+                // Orca:
+                // Lightning infill benefits from always having a bridge layer so don't filter out small unsupported areas. Also, don't filter small internal unsupported areas if the user has requested so.
+                if(!has_lightning_infill && !po->config().dont_filter_internal_bridges){
```
Comment (SoftFever) [inline src/libslic3r/PrintObject.cpp:2030]: Nice handle for the lightning_infill :)

Do you think it would be better to use an area threshold instead of a simple on/off option? I recall having a brief discussion with @Noisyfox previously about this part of the code. The issue we're facing is with 'thin but long' areas that are currently being filtered out, which isn’t ideal. The existing logic doesn't adequately address this. Adding a area threshold should be sufficient to handle these cases.
I would love to hear your thought as well.

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:2030]: Open to do so, but will need guidance on how... Maybe if Noisyfox/you could also push to his PR?

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:2030]: `are you thinking something like this code? 		
```
// Filter out contours with zero area or small area, contours with 2 points only.
        const double min_area_threshold = 0.01 * aoffset2 * aoffset2;
        remove_small(polygons_outer, min_area_threshold);
```

Used here: struct ExPolygonWithOffset
{
public:
    ExPolygonWithOffset(

Reason I didn't try it was because of the comment in the file "NOTE that we cannot filter out polygons worth bridging by their area, because sometimes there is a very small internal island that will grow into large hole".

Or are you thinking of something else?

Comment (SoftFever) [reply src/libslic3r/PrintObject.cpp:2030]: Sure thing.
I should be free to do some experiment after fixing last two issues for 1.9 beta.

Meanwhile here is the rough idea in my mind:
```
              // Orca: calc unsupported area without shrink&expand `lower_layer_solids` and `unsupported_area`
                auto unsupported_area_original   = diff(unsupported_area, lower_layer_solids);
                // By expanding the lower layer solids, we avoid making bridges from the tiny internal overhangs that are (very likely) supported by previous layer solids
                // NOTE that we cannot filter out polygons worth bridging by their area, because sometimes there is a very small internal island that will grow into large hole
                lower_layer_solids = shrink(lower_layer_solids, 1 * spacing); // first remove thin regions that will not support anything
                lower_layer_solids = expand(lower_layer_solids, (1 + 3) * spacing); // then expand back (opening), and further for parts supported by internal solids
                // By shrinking the unsupported area, we avoid making bridges from narrow ensuring region along perimeters.
                unsupported_area   = shrink(unsupported_area, 3 * spacing);
                unsupported_area   = diff(unsupported_area, lower_layer_solids);
                // Orca check threshold
                auto diff = diff(unsupported_area_original, unsupported_area);
                double area_diff = 0.0;
                for(auto p:diff)
                    area_diff += p.area()
                 // check with threshold in setting
                 if(area_diff > BRIDGE_THREASHOLD)
                      unsupported_area   = std::move(unsupported_area_original);
```

Comment (igiannakas) [reply src/libslic3r/PrintObject.cpp:2030]: Cool idea! I'll have a play with it as well tomorrow

**Comment by igiannakas** [comment]
@SoftFever Thank you for this comment above, its been fantastic in pushing me to explore this further (and dont be lazy just disabling it completely.

I'm sharing all of the analysis I've done below for your reading, incl some recommendations. I can push these tonight or tomorrow if you're in agreement.

**Analysis**

I've implemented part of the above proposed code and graphed the polygons so we can see it visually what is going on:
9ae24014-c927-4eec-a990-c79646da6466

The above is at layer 147 of the attached 3MF : 
[Dyson fuss.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13788693/Dyson.fuss.3mf.zip)

At layer 147 (1 indexed) the unsupported_area_original has 8 polygons. There are 2 big polygons (the ones you see) and 6 tiny ones that appear like dots in the graph on the left hand side.

Now if I filter out the tiny ones:
0aa379e3-8671-404b-ac20-556b3bb7d807
We can see the original polygon and the clipped polygon.
Original
`auto unsupported_area_original   = diff(unsupported_area, lower_layer_solids);`
Clipped / New:
```
unsupported_area   = shrink(unsupported_area, 3 * spacing);
unsupported_area   = diff(unsupported_area, lower_layer_solids);
```
The below is the slice:
image

What you are proposing above is to take the delta region between the Original and New polygons (including all the tiny original ones) and if the region is over a specific threshold then replace the New polygon with the Original polygon, reverting the shrinking.

Here is where my potentially questionable memory of math from Computer science classes 22 years ago comes in.

While this will work if the threshold is set low enough, the delta area between the two is a function of:
1. 3 * spacing - this is constant
2. The size of the polygon. Larger polygons will reduce in terms of surface area much more compared to smaller ones

So setting a threshold area as a filtering mechanism won't necessarily work. We could do it as a % but then this is already kind of known because we always shrink by 3*spacing. (I think).

**What we **could** do is shrink the polygon by less - not 3x spacing but say 1x spacing** in which case we get this shrinkage:

3fa52cfa-bb95-43d7-822f-ee09d71f6c6f

But this doesnt help as the region that would trigger the bridge on the left is clipped more (this is with 1x spacing). (you can see it as the distance from the original polygon on the left compared to the red dotted line is proportionally larger).

image

**We could go even lower than that - say half spacing: (the black line)**
516a5b78-d50c-4abc-ac7f-f62bd9d5d95f

In this case we finally get some bridging going on but that quickly deteriorates on subsequent layers
image

image

That is now because of the clipping from the lower_layer_solids that are expanded by 3*spacing.

If I reduce the expansion of the lower_layer_solids to 1xspacing and leave the unsupported area clipped by 1x spacing I get good bridges again:

image


ca094cb4-67df-43f2-a588-45a90b42f343


**So where does this leave us?**

A few options depending on how much tweaking we leave to the user.
1. We cannot use the area difference I think because of the above reasons (difference is proportional to the size of the polygon)
2. We can either give the user a spacing option that is a % between 0-100 which is then multiplied with the 3*spacing to control that filtering
3. Or we could give an on-off switch that sets the spacing to 1x or 3x (default).

**Comment by igiannakas** [comment]
Updated some minor errata on the above analysis + submitted new code.

**Comment by neorm** [comment]
Ok, I have checked some of the generated G-code. Some of it looks a bit weird sometimes, is there a way to make it a bit more uniform?
image
image
image
image

**Comment by neorm** [comment]
Also, I tested it with a part where the slope is increasing. Around layer 25, it stops making the bridge layers, and when it prints these small lines, they tend to curl upwards as they cool down. That's when it becomes a problem.
[Bambu_Lab_Trash_-_Small_-_Thickness_1mm.zip](https://github.com/SoftFever/OrcaSlicer/files/13791988/Bambu_Lab_Trash_-_Small_-_Thickness_1mm.zip)
image

**Comment by igiannakas** [comment]
The downside to removing the filtering is that you may get small sections that are not that uniform. This is dependant on the model geometry unfortunately and is a tradeoff to be made - more bridging with some small artefacts or reduced bridging with none. Think this is making the case to have this as an option for the user.

I haven't found a way to trigger bridging on your second scenario, even when removing completely all filtering. The reason for this is that its a single perimeter width that is unsupported, which doesnt "count" as an unsupported region large enough to trigger bridging. 

Theoretically it shouldn't affect print quality as the vast majority of the surface is supported underneath. Kind of like printing small overhangs. This can be mitigated by ensuring enough top layers are present as this will push those small overhangs down and not be visible to the outside.

Unless Softfever has another idea on this? :)

**Comment by igiannakas** [comment]
Doing a print test with the below problem area only:
[Slope print test.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13792251/Slope.print.test.3mf.zip)


image

Print speeds are reasonably fast and infill is very low - 6%, to show the issue if present and will revert back

**Comment by igiannakas** [comment]
Printer go brrrrr :D 

https://youtube.com/shorts/Xh_-R8LBpao?si=sqjdzbnGvdOtyuyP

I can see every so slight curling up in the layers without support. Will try to find where I can fix this, but I'm not holding my breath. Part so far looks OK.

**Comment by igiannakas** [comment]
So turns out you're absolutely correct - the top surface looked like poop because of the curling.

I've extended the removal of the filtering even further resulting in this:

image

While this option doesn't "break" the model it does mean that it creates very conservative internal bridges, increasing print time in some cases potentially unnecessarily. Hence why this now must be an option and not on by default.

I've pushed a new build for testing.

**Comment by igiannakas** [comment]
New build is up. @neorm please test when you can, ideally also with a real print, if possible.

Flagged option as experimental and updated tooltip with the warning that it may unnecessarily create internal bridges over small overhanging solid infill regions. However, it does have a use case like the above example:

**Disabled:**
IMG_2747

**Enabled:**
(will update comment shortly with print result)

**Comment by igiannakas** [comment]
@SoftFever I'll make a further change to this PR this week. I want to introduce a drop down for this option that controls the level of filtering. 
**1. Disabled** - the as is V1.9 code
**2. Limited filtering** - would be the PR as it was submitted a couple of weeks ago - where it works for partly slanted surfaces but not all slanted surfaces
**3. No filtering** - would be this PR as it is now

I'll be making the changes this week and I'll resubmit. The reasoning is that I want to enable this option in my own personal profiles for slanted surfaces but I am not a fan of the complete lack of filtering as this PR stands right now. I can see the need for no filtering on some difficult models, so its valid to keep it, but I dont want to be throwing bridges everywhere if a less aggressive option can work for the model.

**Comment by SoftFever** [comment]
> @SoftFever I'll make a further change to this PR this week. I want to introduce a drop down for this option that controls the level of filtering. **1. Disabled** - the as is V1.9 code **2. Limited filtering** - would be the PR as it was submitted a couple of weeks ago - where it works for partly slanted surfaces but not all slanted surfaces **3. No filtering** - would be this PR as it is now
> 
> I'll be making the changes this week and I'll resubmit. The reasoning is that I want to enable this option in my own personal profiles for slanted surfaces but I am not a fan of the complete lack of filtering as this PR stands right now. I can see the need for no filtering on some difficult models, so its valid to keep it, but I dont want to be throwing bridges everywhere if a less aggressive option can work for the model.

Noted.
👍

**Comment by Noisyfox** [comment]
Looks very promising! Good job!

**Comment by igiannakas** [comment]
So updated the PR to convert this into an option:

**Disabled (default) - Limited filtering - No filtering**
Limited filtering addresses the majority of the slanted top surface issues without creating unnecessary internal bridges and is what I'll pick as my default. No filtering is very aggressive in creating internal bridges but this solves issues with very specific models with slanted top surfaces as seen above.
image

Submitting as ready for review and I'll update the top post with the final implementation.

**Comment by SoftFever** [comment]
> So updated the PR to convert this into an option:
> 
> **Disabled (default) - Limited filtering - No filtering** Limited filtering addresses the majority of the slanted top surface issues without creating unnecessary internal bridges and is what I'll pick as my default. No filtering is very aggressive in creating internal bridges but this solves issues with very specific models with slanted top surfaces as seen above. image
> 
> Submitting as ready for review and I'll update the top post with the final implementation.

Thanks for the great work! 
I messed with a few models and agree that the 'limited' option seems most reasonable from the g-code preview, even though it slightly increases printing time.
I'm not sure how much difference it will make to the actual print for most 'common' models, but I totally agree with you on keeping the current default behavior.

**Review by SoftFever — APPROVED** [review]

**Comment by igiannakas** [comment]
Fantastic 👌🏻 thank you!

I’ve set the limited option as my default for my custom profiles and will be test driving this going forward. Maybe we revisit the default when more data is available.

**Comment by TinyMito** [comment]
@igiannakas I just want to chip in saying this is an awesome work and thank you. Not just solved slope in an angle surface artifact, but there are instances just 20 degree straight slope can see the improvement by having **no filtering** set. It works like a charm!

compare

**Comment by igiannakas** [comment]
> @igiannakas I just want to chip in saying this is an awesome work and thank you. Not just solved slope in an angle surface artifact, but there are instances just 20 degree straight slope can see the improvement by having **no filtering** set. It works like a charm!
> 
> compare

Your welcome! Personally I have set my profile to limited filtering as this works great for most cases with the odd exception needing none, and equally the odd exception needing this feature disabled. Big improvement in sloped surfaces over the past few months I’ve been using this

**Comment by borris345** [comment]
no filtering works great on this model attached but with limited is poor. any help? i dont like how much extra time and filament it uses so hopefully this will help you improve it! this is one of best features added just need get some testing and tuning.

model used https://www.dropbox.com/scl/fi/oynw87altq5yma6vqscdy/gradient-test.3mf?rlkey=61qcutklydx4wm7yvnxfnooft&dl=0

**Comment by vgdh** [comment]
WOW! internal bridges looks very well!

**Comment by igiannakas** [comment]
> no filtering works great on this model attached but with limited is poor. any help? i dont like how much extra time and filament it uses so hopefully this will help you improve it! this is one of best features added just need get some testing and tuning. i stopped the test early because it was quite obvious it was going to be perfect with it turned on compared to before.
> 
> model used https://www.dropbox.com/scl/fi/oynw87altq5yma6vqscdy/gradient-test.3mf?rlkey=61qcutklydx4wm7yvnxfnooft&dl=0
> 
> 

Not much that can be done really - for models like this is why I implemented the no filtering option. It’s a trade off- more print time but better quality.

**Comment by martian099** [comment]
That's a huge difference in print quality! Yeah I noticed that too that no
filtering consumes way too much filament and time, and unnecessary in most
but not all cases. I have two comments

1. If there's a way to automatically decide no filtering vs limited
filtering, that would be great, so we don't need to experiment and this
will give us ease of mind. Users don't even need to worry about this toggle
if it's automatic selection

2. Instead of relying solely on internal bridges, I'd recommend slowing
down the internal overhangs like how we slow down the external overhangs.
This could remove need for internal bridges in lots of cases.

**Comment by igiannakas** [comment]
I wish it was that simple… two things that prevent this from getting more user friendly:
1. The slicer doesn’t understand internal overhangs. When slicing a model the internal sparse infill is considered as a support surface hence it doesn’t consider overhanging perimeters as overhanging, because they are facing into a “solid”. For all intents and purposes the inside of the model is “solid” hence it cannot overhang if that makes sense. That is a limitation of the current code base and will need significant rewrite for that to change - which has wider consequences (among others, it will increase the difficulty in porting features from Prusa, Bambu and Superslicer).

2. The slicer makes a tradeoff between supporting all internal surfaces or applying some filtering to remove the need for too many bridges. That filtering is quite complicated as shown in the study earlier in this thread. And in some edge cases it removes too much of the internal bridge, hence where this option comes in. If there was a way to automate this and make it transparent I would have done it already :(. The best tradeoff is to use limited filtering that would cover the large majority of scenarios.  For models with sharp slanted surfaces inspect the sliced file and judge whether you’ll want more internal bridges or not. Then apply them manually. 

I did try setting this more automatically but it cannot be done with the current code base without some significant rework of the bridging code which would introduce the potential for more issues coming up. 

This is also the reason why none of the other 3 slicers using the same code base have fixed this…

**Comment by jrmhughes** [comment]
I am using this feature for the first time. It was very successful at fixing the issues I had in the top surface of my print but it didn't work for my model when I used a 0.08mm layer height.

I am using default settings for Bambu P1S, Generic PETG, 0.12mm Fine. The right hand one in the screenshots is 0.12mm layer height. The left is 0.08mm layer height. I have set 'Don't filter out small internal bridges (beta)' to 'No filtering'.
It worked as I expected with 'no filtering' or 'limited filtering' with 0.12mm layer height but not 0.08mm.

Can anyone explain why this is?

0.08mm layer height (left) and 0.12mm layer height (right)
**Screenshot 1:** Internal bridges were created on the slanted surface with the 0.12mm layer height but not the 0.08mm
Slant
**Screenshot 2:** Internal bridges were created with both layer heights for a couple of layers above and below the slanted surface (where the rounded corners are).
Above slant
**Screenshot 3:** The full model
Full model

**Comment by neorm** [comment]
I agree, I'm very happy with the implementation. This way, I can handle these kinds of problems. Just wanted to say thank you, @igiannakas

**Comment by igiannakas** [comment]
@neorm your welcome!! Hope it helps you ;)

@jrmhughes unfortunately it doesn’t work always when the layer height transition is too low compared to the slope. Try with filtering fully “disabled” and let’s see whether that makes any difference

**Comment by jrmhughes** [comment]
@igiannakas Thanks for replying. And thank you for all the work you've done improving orcaslicer.
The above screenshots were with '"No Filtering". If I set "don't filter out small internal bridges" to "disabled", no internal bridging is generated anywhere except the flat top (see screenshot below).
Only on roof



I did some more investigation and it seems that, as you say, the layer height is too small compared to the slope (which was 13.2 degrees). I created a table to show the limit of when it generates:
[Test 4 table.pdf](https://github.com/user-attachments/files/17006678/Test.4.table.pdf)

I don't know if this was the right place to ask because it seems it's not to do with the filtering, but rather the creation of the bridging layers to begin with. Maybe I should create a feature request for adjusting the overlap width at which they generate because I like to use 0.08mm layer height for printing moulds but sometimes get a wavy surface on shallow angles. I don't know how it works though or whether that would be possible.

**Comment by igiannakas** [comment]
Another way to deal with this is to slow down your internal solid infill.  It ideal speed wise but setting your internal solid infill and inner walls to a more conservative speed should address the visual artefacts. And it will help with precision especially at 0.08 mm LH

**Comment by jrmhughes** [comment]
Thanks for the tip

**Comment by Finnitio** [comment]
Is there a way to adjust the filter more precisely? Like a parameter instead of a dropdown? I have surface problems with a curved and shallow part. When in set the filter to moderately nothing happens. Whhen I switch filtering off too many bridges are created and the printtime doubles.
 
image
image
