### PR TITLE
Fix: The correct build plate is being selected in the UI on project loading

### LINKED ISSUE #11966: UI: Wrong plate is being selected in UI after 3MF project loading
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2-dev

### Operating System (OS)

Windows

### OS Version

11

### Additional system information

_No response_

### Printer

Bambulab A1 mini

### How to reproduce

1. Create a new empty project or load the existing one.
2. Select the BBL printer and the `Cool Plate (SuperTack)` plate and save the project.
3. Relaunch OrcaSlicer (optional) and load the project.
4. Check what plate is selected in UI.

Note: the plate type is being loaded correctly; it seems that the related UI part is not being updated properly on load.

### Actual results

Image

### Expected results

Image

### Project file & Debug log uploads

An empty project with all the default params, but the Cool Plate was selected:

- [Test.zip](https://github.com/user-attachments/files/24651789/Test.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by valerii-bokhan**
# Description

Fixes: #11966

Fixed the build plate type setting during project load.

Implemented the code solution suggested by @kisslorand

### CODE REVIEW

**Comment by valerii-bokhan** [comment]
Hey @ianalexis, I mentioned you because you wanted to look into this issue.

**Review by kisslorand — CHANGES_REQUESTED** [review]
.

File: src/slic3r/GUI/Plater.cpp [hunk 1]
```diff
@@ -3145,9 +3145,18 @@ bool Sidebar::is_new_project_in_gcode3mf()
 
 void Sidebar::on_bed_type_change(BedType bed_type)
 {
-    // btDefault option is not included in global bed type setting
-    int sel_idx = (int)bed_type - 1;
-    if (p->combo_printer_bed != nullptr) p->combo_printer_bed->SetSelection(sel_idx);
+    if (p->combo_printer_bed == nullptr)
```
Comment (kisslorand) [inline src/slic3r/GUI/Plater.cpp:3150]: I suggest a comment here:
`// Map BedType to the current combo list (some printers filter types).`

**Review by kisslorand — CHANGES_REQUESTED** [review]

File: src/slic3r/GUI/Plater.cpp (hunk 1 above)
Comment (valerii-bokhan) [reply src/slic3r/GUI/Plater.cpp:3150]: Fixed

Comment (kisslorand) [reply src/slic3r/GUI/Plater.cpp:3150]: Thank you.

**Review by kisslorand — APPROVED** [review]
LGTM

**Comment by Sabriel-Koh** [comment]
Tested this as well and seems to be good

**Review by SoftFever — APPROVED** [review]
LGTM

Thank you!
