### PR TITLE
Fix stealthmode

### LINKED ISSUE #13049: Stealth Mode still connects to api.bambulab.com and does not check HTTPS certificate
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2

### Operating System (OS)

Linux

### OS Version

Opensuse Tumbleweed

### Additional system information

_No response_

### Printer

Doesn't matter

### How to reproduce

1. Start OrcaSlicer with Stealth Mode enabled
2. Use MITMProxy to check HTTPS requests

### Actual results

1. OrcaSlicer connects to api.bambulab.com with a GET request:

```
GET https://api.bambulab.com/v1/iot-service/api/slicer/resource?slicer/printer/bbl=01.10.00.00 HTTP/1.1
Host: api.bambulab.com
User-Agent: OrcaSlicer/2.3.2
```

2. Also even with an invalid HTTPS certificate (MITMProxy enabled, but CA not installed) it connects fine. Normally you have to trust the MITMProxy CA which I did not in this test case. This normally should prevent network interception.

### Expected results

1. Should not connect at all to api.bambulab.com
2. Should check if certificate chain is valid

### Project file & Debug log uploads

Doesn't matter

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Anything else?

There is already a ticket about the Stealth Mode here: https://github.com/OrcaSlicer/OrcaSlicer/issues/6102 but it has been closed due to inactivity.

I really would like to have a real stealth mode and at least the HTTPS check should work correctly.

### PR DESCRIPTION
**Pull request by RF47**
This pull request introduces several improvements to how the application handles "stealth mode". The main changes ensure that when stealth mode is enabled, the application avoids making network connections or cloud syncs.

Fix #13049

### CODE REVIEW

**Comment by Felix14-v2** [comment]
Will this only block Bambu telemetry or self-hosted synchronization servers as well (#12931)? Or that depends on implementation of the mentioned PR?

**Comment by RF47** [comment]
> Will this only block Bambu telemetry or self-hosted synchronization servers as well (12931)? Or that depends on implementation of the mentioned PR?

The idea is to block only the Bamboo telemetry, but I'm not sure if it might affect other connections, so we need to test this to make sure it doesn't break anything.

File: src/slic3r/Utils/Http.cpp [hunk 1]
```diff
@@ -194,8 +194,8 @@ Http::priv::priv(const std::string &url)
 #ifdef __WINDOWS__
 	::curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_MAX_TLSv1_2);
 #endif
-	::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
-	::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
+   ::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
+	::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
```
Comment (ianalexis) [inline src/slic3r/Utils/Http.cpp]:
```suggestion
	::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
	::curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
```

Comment (ianalexis) [reply src/slic3r/Utils/Http.cpp]: I think we must keep 0L until (if needed) we update this file like BBS did.

File: src/slic3r/GUI/GUI_App.cpp [hunk 2]
```diff
@@ -1005,11 +1005,13 @@ void GUI_App::post_init()
...
-            this->preset_updater->sync(http_url, language, network_ver, sys_preset ? preset_bundle : nullptr);
+            if (!app_config->get_stealth_mode()) {
+                std::string http_url = get_http_url(app_config->get_country_code());
+                std::string language = GUI::into_u8(current_language_code());
+                std::string network_ver = Slic3r::NetworkAgent::get_version();
+                bool        sys_preset  = app_config->get("sync_system_preset") == "true";
+                this->preset_updater->sync(http_url, language, network_ver, sys_preset ? preset_bundle : nullptr);
+            }
 
             this->check_new_version_sf();
```
[the remark this answers is not in the document]
Comment (RF47) [reply src/slic3r/GUI/GUI_App.cpp:1016]: The stealth mode is just for block BBL cloud services.

**Comment by RF47** [comment]
@valerii-bokhan could you try this?

**Comment by valerii-bokhan** [comment]
I hope I can test it tomorrow. Do you have any specific test scenario in mind?

**Comment by RF47** [comment]
> I hope I can test it tomorrow. Do you have any specific test scenario in mind?

Verify that Bambulab services continue to function if Stealth Mode is disabled, and vice versa

**Comment by RF47** [comment]
@sebastianha Could you try this version? I can't get it to verify the certificates properly, so it should just avoid connecting to BBL.

**Comment by sebastianha** [comment]
Just tested it and it works fine.

When enabling stealth mode it only connects to "https://check-version.orcaslicer.com/latest" but nothing else.

Connectivity tests also work fine, though the HTTPS certificate is not being checked (as you already said).

So this definitely fixes the connection to bambulab, thanks for your work!

**Review by SoftFever — APPROVED** [review]
Thank you!
