### PR TITLE
WIP fix sacrificial layer.cpp

### LINKED ISSUE #12953: Bridge counterbore holes, wall missing
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.2 and earlier

### Operating System (OS)

Windows

### OS Version

win 11

### Additional system information

_No response_

### Printer

My own produced Core XZ

### How to reproduce

1. Paste model
2. Bridge counterbore holes setting, set partialy bridging or sacrificial bridging
3. Slice layers
4. See the problem
### Actual results

If partialy bridged or sacrificial layer is select, then walls are missing. Model is weak and broke

### Expected results

If partialy bridged or sacrificial layer is select, then wall is exist.

### Project file & Debug log uploads

[Solar lámpa bura_sima.zip](https://github.com/user-attachments/files/26254047/Solar.lampa.bura_sima.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Anything else?

Image

### PR DESCRIPTION
**Pull request by RF47**
# Fix sacrificial layer edgecase , with 2 perimeters only
Adjusts the sacrificial bridge layer (“counterbore hole bridging”) geometry handling to address an edge case where walls disappear when only 2 perimeters are present 
Is no longer needed a modifier to proper bridge detection.

Known issues (see comments below)
the one perimeter case is not adressed.

root cause:
When there are only two perimeters, this filter consumes the entire ExPolygon, which is why the bridges are not generated

https://github.com/OrcaSlicer/OrcaSlicer/blob/f72de427cb4920285fa7b4f3e6e4e5e7f7b6dddc/src/libslic3r/PerimeterGenerator.cpp#L1714-L1715

# Screenshots/Recordings/Graphs
Before:
image
image

After:
image
image
image

## Tests

[test sacrificial layer.zip](https://github.com/user-attachments/files/26335429/test.sacrificial.layer.zip)

Fix #12953

### CODE REVIEW

**Comment by RF47** [comment]
known issues 1:
Note: In Classic Wall Generator, the perimeters overlap on the bridging layer; I’m not yet sure how to fix this, but it’s still better than the current behaviour.
image
(this behavior is present in the current code)

File: src/libslic3r/PerimeterGenerator.cpp [hunk 1]
```diff
@@ -1754,9 +1758,11 @@ void PerimeterGenerator::process_no_bridge(Surfaces& all_surfaces, coord_t perim
                                         unsupported_filtered.erase(unsupported_filtered.begin() + i);
                                     }
                                 }
-                                unsupported_filtered = intersection_ex(last,
-                                                                       offset2_ex(unsupported_filtered, double(-perimeter_spacing / 2), double(bridged_infill_margin + perimeter_spacing / 2)));
                                 if (this->config->counterbore_hole_bridging.value == chbFilled) {
+                                    // Expand sacrificial layer bridge area to ensure proper anchoring of the bridge infill.
+                                    unsupported_filtered = offset_ex(unsupported_filtered, double(perimeter_spacing));
+                                    // Clip expanded unsupported regions back to the current surface to avoid fill outside the part.
+                                    unsupported_filtered = intersection_ex(unsupported_filtered, ExPolygons() = { surface->expolygon });
```
Comment (RF47) [inline src/libslic3r/PerimeterGenerator.cpp]: This is dangerous; if the intersection returns null, it will definitely cause a crash.
```suggestion

```

**Review by kisslorand — CHANGES_REQUESTED** [review]
```
// Keep the expanded bridge region inside the current surface.
unsupported_filtered = intersection_ex(unsupported_filtered, last);
```

File: src/libslic3r/PerimeterGenerator.cpp [hunk 2]
```diff
@@ -1754,9 +1758,9 @@ void PerimeterGenerator::process_no_bridge(Surfaces& all_surfaces, coord_t perim
                                         unsupported_filtered.erase(unsupported_filtered.begin() + i);
                                     }
                                 }
-                                unsupported_filtered = intersection_ex(last,
-                                                                       offset2_ex(unsupported_filtered, double(-perimeter_spacing / 2), double(bridged_infill_margin + perimeter_spacing / 2)));
                                 if (this->config->counterbore_hole_bridging.value == chbFilled) {
+                                    // Expand sacrificial layer bridge area to ensure proper anchoring of the bridge infill.
+                                    unsupported_filtered = offset_ex(unsupported_filtered, double(perimeter_spacing));
```
Comment (kisslorand) [inline src/libslic3r/PerimeterGenerator.cpp]: Add this clamp also:
```
// Keep the expanded bridge region inside the current surface.
unsupported_filtered = intersection_ex(unsupported_filtered, last);
```

**Review by kisslorand — CHANGES_REQUESTED** [review]

**Comment by kisslorand** [comment]
> Note: In Classic Wall Generator, the perimeters overlap on the bridging layer; I’m not yet sure how to fix this, but it’s still better than the current behavior. 

What if we use only 1 wall there?

**Comment by RF47** [comment]
> > Note: In Classic Wall Generator, the perimeters overlap on the bridging layer; I’m not yet sure how to fix this, but it’s still better than the current behavior.
> 
> What if we use only 1 wall there?

That would be ideal, but I still haven't managed it

**Comment by RF47** [comment]
known issues 2:
problem (even  intersecting with last) :
image
superslicer has the same issue:
image
Orca 232 has the same issue:
image

File: src/libslic3r/PerimeterGenerator.cpp (hunk 2 above)
Comment (RF47) [reply src/libslic3r/PerimeterGenerator.cpp]: its done, i just keep the original intersection in line 1761

**Review by SoftFever — APPROVED** [review]
LGTM
Thank you
